<a href="https://colab.research.google.com/github/seema1977/seemanew/blob/seema3/day3prog.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10]) 
print(ds)


0     2
1     4
2     6
3     8
4    10
dtype: int64


In [5]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)


Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [6]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [7]:
import pandas as pd
d1 = {'a': 100, 'b': 200, 'c':300, 'd':400, 'e':800}
print("Original dictionary:")
print(d1)
new_series = pd.Series(d1)
print("Converted series:")
print(new_series)


Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64


In [8]:
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)


NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [9]:
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:")
print(s1)
print("Change the said data type to numeric:")
s2 = pd.to_numeric(s1, errors='coerce')
print(s2)


Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


In [10]:
import numpy as np
s1 = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']


In [2]:
#Write a Pandas program to sort a given Series.
import pandas as pd
s = pd.Series(['200','100','python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)


Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
1       100
0       200
3    300.12
4       400
2    python
dtype: object


In [3]:
#Write a Pandas program to add some data to an existing Series.

import pandas as pd
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
print("\nData Series after adding some data:")
new_s = s.append(pd.Series(['500', 'php']))
print(new_s)


Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object


In [4]:
#Write a Pandas program to create a subset of a given series based on value and condition.

import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


In [5]:
#Write a Pandas program to create a subset of a given series based on value and condition.

import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s >n]
print(new_s)


Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
7      7
8      8
9      9
10    10
dtype: int64


In [6]:
#Write a Pandas program to change the order of index of a given series.
import pandas as pd
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
print("Original Data Series:")
print(s)
s = s.reindex(index = ['B','A','C','D','E'])
print("Data Series after changing the order of index:")
print(s)


Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


In [7]:
#Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series.

import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())


Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565


In [8]:
#Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [10]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[ 1.12812499  0.11287845 -0.00436305 -0.31976273  0.08580959]


In [11]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[11 13 29 25 13 17]


In [12]:
#Write a NumPy program to create a 3x3x3 array with random values.
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.26696338 0.23297707 0.64497763]
  [0.89579392 0.39828769 0.83385741]
  [0.31568349 0.73790029 0.28923486]]

 [[0.09448647 0.71477685 0.32103364]
  [0.2294149  0.48569041 0.26388283]
  [0.73422784 0.52010583 0.52003523]]

 [[0.74034576 0.39953032 0.16239641]
  [0.6222325  0.88885292 0.95203365]
  [0.97012436 0.90770247 0.9980419 ]]]


In [13]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.60796179 0.11523998 0.67201322 0.73074711 0.01162683]
 [0.85492943 0.23711244 0.43471068 0.74961662 0.63397346]
 [0.83023845 0.19638195 0.7820306  0.18722811 0.06756231]
 [0.20295865 0.03101444 0.80862616 0.504859   0.87580118]
 [0.11844307 0.66543169 0.72796744 0.08523117 0.60139926]]
Minimum and Maximum Values:
0.011626834706739642 0.8758011778468271


In [14]:
#Write a NumPy program to create a random 10x4 array and extract the first five rows of the # array and store them into a variable.
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)


Original array: 
[[0.54451831 0.86771104 0.99920638 0.72156573]
 [0.38204698 0.29946989 0.63336371 0.91849589]
 [0.60015206 0.05047171 0.02461531 0.11298943]
 [0.78841532 0.10442566 0.06082903 0.52151337]
 [0.86080196 0.59085959 0.61673117 0.20016476]
 [0.49709351 0.33191318 0.01376563 0.31216885]
 [0.28278584 0.70789494 0.68349589 0.4210875 ]
 [0.2125552  0.0324704  0.98250345 0.46906806]
 [0.91277613 0.55881579 0.01795074 0.81231724]
 [0.94902189 0.65206567 0.05211422 0.36570785]]
First 5 rows of the above array:
[[0.54451831 0.86771104 0.99920638 0.72156573]
 [0.38204698 0.29946989 0.63336371 0.91849589]
 [0.60015206 0.05047171 0.02461531 0.11298943]
 [0.78841532 0.10442566 0.06082903 0.52151337]
 [0.86080196 0.59085959 0.61673117 0.20016476]]
First 3 columns of the above array:
[[0.54451831 0.86771104 0.99920638 0.72156573]
 [0.38204698 0.29946989 0.63336371 0.91849589]
 [0.60015206 0.05047171 0.02461531 0.11298943]
 [0.78841532 0.10442566 0.06082903 0.52151337]
 [0.86080196 0.5908

In [4]:
import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10]) 
print(ds)
print(type(ds))
print("Convert Pandas Series to Python list")
print(ds.tolist())
print(type(ds.tolist()))


0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>
